feeder: feeder.feeder.LandscapeDataset

train_feeder_args:
  metadata_path: feeder/train.csv
  test_mode: False

test_feeder_args:
  metadata_path: feeder/test.csv
  test_mode: True


# model
model: model.resnet101.ResNet101
model_args:
  num_class: 15

#optim
weight_decay: 0.0001
base_lr: 0.2
lr_decay_rate: 0.1
step: [50]

# training
device: [0]
batch_size: 16
test_batch_size: 64
num_epoch: 20
nesterov: True
warm_up_epoch: 5